=== Sybar/Hammer/L2J_Mobius_Essence_8.3_Guardians/dist/game/data/xsd/AdenLaboratoryData.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="boss" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="game" maxOccurs="unbounded" minOccurs="3">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="page" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="options" maxOccurs="unbounded" minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="stage" maxOccurs="unbounded" minOccurs="1">
																	<xs:complexType>
																		<xs:attribute type="xs:int" name="level" use="required" />
																		<xs:attribute type="xs:float" name="chance" use="required" />
																		<xs:attribute type="xs:int" name="primarySkillLevel" use="required" />
																		<xs:attribute type="xs:int" name="secondarySkillLevel" use="optional" />
																		<xs:attribute type="xs:int" name="combatPower" use="optional" />
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute type="xs:int" name="maxLevel" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:int" name="index" use="required" />
												<xs:attribute type="xs:float" name="successRate" use="required" />
												<xs:attribute type="xs:int" name="cardCount" use="optional" />
												<xs:attribute type="xs:int" name="primarySkillId" use="required" />
												<xs:attribute type="xs:int" name="secondarySkillId" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="type" use="required" />
									</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:int" name="index" use="required" />
						<xs:attribute type="xs:int" name="specialSlotsCount" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sybar/Hammer/L2J_Mobius_Essence_8.3_Guardians/dist/game/data/AdenLaboratoryData.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/AdenLaboratoryData.xsd">
	<boss index="1" specialSlotsCount="4"> <!-- Queen Ant -->
		<game type="NORMAL">
		<!--
		 - Success rate: 1.0 = 100% !!! Cannot be lower than 0.0000001% !!! Max 7 digits after the decimal
		 - Index: slotID in the client.
		 -->
			<page index="1" cardCount="3" successRate="0.3" primarySkillId="85701">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="2" cardCount="8" successRate="0.125" primarySkillId="85702">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="3" cardCount="13" successRate="0.077" primarySkillId="85703">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="4" cardCount="18" successRate="0.056" primarySkillId="85704">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="6" cardCount="20" successRate="0.050" primarySkillId="85705">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="7" cardCount="22" successRate="0.045" primarySkillId="85706">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="8" cardCount="24" successRate="0.042" primarySkillId="85707">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="9" cardCount="26" successRate="0.038" primarySkillId="85708">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="11" cardCount="28" successRate="0.036" primarySkillId="85709">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="12" cardCount="30" successRate="0.033" primarySkillId="85710">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="13" cardCount="32" successRate="0.031" primarySkillId="85711">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="14" cardCount="34" successRate="0.029" primarySkillId="85712">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="15" cardCount="36" successRate="0.027" primarySkillId="85713">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="17" cardCount="36" successRate="0.025" primarySkillId="85714">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="18" cardCount="36" successRate="0.025" primarySkillId="85715">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="19" cardCount="36" successRate="0.025" primarySkillId="85716">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="20" cardCount="36" successRate="0.025" primarySkillId="85717">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="22" cardCount="36" successRate="0.023" primarySkillId="85718">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="23" cardCount="36" successRate="0.023" primarySkillId="85719">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<page index="24" cardCount="36" successRate="0.023" primarySkillId="85720">
				<options>
					<stage level="1" chance="1" primarySkillLevel="1" />
				</options>
			</page>
			<!-- END. A total of 24 normal games. -->
		</game>
		<game type="SPECIAL"> <!-- `type` must always be in ALL-CAPS! -->
			<page index="5" successRate="100" primarySkillId="85721">
				<options maxLevel="20">
					<!-- Each chance point = 0.01 in the client, so we multiply by 10000 before we send the server packet. -->
					<stage level="01" chance="0.1000" primarySkillLevel="1" combatPower="1" /> <!-- 10% -->
					<stage level="02" chance="0.1000" primarySkillLevel="2" combatPower="1" /> <!-- 10% -->
					<stage level="03" chance="0.1000" primarySkillLevel="3" combatPower="1" /> <!-- 10% -->
					<stage level="04" chance="0.1000" primarySkillLevel="4" combatPower="1" /> <!-- 10% -->
					<stage level="05" chance="0.1000" primarySkillLevel="5" combatPower="1" /> <!-- 10% -->
					<stage level="06" chance="0.1000" primarySkillLevel="6" combatPower="1" /> <!-- 10% -->
					<stage level="07" chance="0.1000" primarySkillLevel="7" combatPower="1" /> <!-- 10% -->
					<stage level="08" chance="0.0820" primarySkillLevel="8" combatPower="1" /> <!-- 8.2% -->
					<stage level="09" chance="0.0820" primarySkillLevel="9" combatPower="1" /> <!-- 8.2% -->
					<stage level="10" chance="0.0600" primarySkillLevel="10" combatPower="1" /> <!-- 6% -->
					<stage level="11" chance="0.0300" primarySkillLevel="11" combatPower="1" /> <!-- 3% -->
					<stage level="12" chance="0.0100" primarySkillLevel="12" combatPower="1" /> <!-- 0.1% -->
					<stage level="13" chance="0.0100" primarySkillLevel="13" combatPower="1" /> <!-- 0.1% -->
					<stage level="14" chance="0.0080" primarySkillLevel="14" combatPower="1" /> <!-- 0.8% -->
					<stage level="15" chance="0.0070" primarySkillLevel="15" combatPower="1" /> <!-- 0.7% -->
					<stage level="16" chance="0.0050" primarySkillLevel="16" combatPower="1" /> <!-- 0.5% -->
					<stage level="17" chance="0.0025" primarySkillLevel="17" combatPower="1" /> <!-- 0.25% -->
					<stage level="18" chance="0.0020" primarySkillLevel="18" combatPower="1" /> <!-- 0.2% -->
					<stage level="19" chance="0.0010" primarySkillLevel="19" combatPower="1" /> <!-- 0.1% -->
					<stage level="20" chance="0.0005" primarySkillLevel="20" combatPower="1" /> <!-- 0.05% -->
				</options>
			</page>
			<page index="10" successRate="100" primarySkillId="85722">
				<options maxLevel="50">
					<!-- Each chance point = 0.01, so we multiply by 100 before we send the server packet. -->
					<stage level="01" chance="0.0700" primarySkillLevel="1" combatPower="3" />
					<stage level="02" chance="0.0600" primarySkillLevel="2" combatPower="3" /> <!-- 6.0% -->
					<stage level="03" chance="0.0565" primarySkillLevel="3" combatPower="3" /> <!-- 5.65% -->
					<stage level="04" chance="0.0500" primarySkillLevel="4" combatPower="3" /> <!-- 5.0% -->
					<stage level="05" chance="0.0500" primarySkillLevel="5" combatPower="3" />
					<stage level="06" chance="0.0400" primarySkillLevel="6" combatPower="3" /> <!-- 4.0% -->
					<stage level="07" chance="0.0400" primarySkillLevel="7" combatPower="3" />
					<stage level="08" chance="0.0400" primarySkillLevel="8" combatPower="3" />
					<stage level="09" chance="0.0400" primarySkillLevel="9" combatPower="3" />
					<!-- above should be 44.65% -->
					<stage level="10" chance="0.0250" primarySkillLevel="10" combatPower="3" /> <!-- 2.5% -->
					<stage level="11" chance="0.0250" primarySkillLevel="11" combatPower="3" />
					<stage level="12" chance="0.0250" primarySkillLevel="12" combatPower="3" />
					<stage level="13" chance="0.0250" primarySkillLevel="13" combatPower="3" />
					<stage level="14" chance="0.0250" primarySkillLevel="14" combatPower="3" />
					<stage level="15" chance="0.0225" primarySkillLevel="15" combatPower="3" /> <!-- 2.25% -->
					<stage level="16" chance="0.0225" primarySkillLevel="16" combatPower="3" />
					<stage level="17" chance="0.0225" primarySkillLevel="17" combatPower="3" />
					<stage level="18" chance="0.0225" primarySkillLevel="18" combatPower="3" />
					<stage level="19" chance="0.0225" primarySkillLevel="19" combatPower="3" />
					<stage level="20" chance="0.0200" primarySkillLevel="20" combatPower="3" /> <!-- 2.0% -->
					<stage level="21" chance="0.0200" primarySkillLevel="21" combatPower="3" />
					<stage level="22" chance="0.0200" primarySkillLevel="22" combatPower="3" />
					<stage level="23" chance="0.0200" primarySkillLevel="23" combatPower="3" />
					<stage level="24" chance="0.0200" primarySkillLevel="24" combatPower="3" />
					<stage level="25" chance="0.0140" primarySkillLevel="25" combatPower="3" /> <!-- 1.4% -->
					<stage level="26" chance="0.0140" primarySkillLevel="26" combatPower="3" />
					<stage level="27" chance="0.0140" primarySkillLevel="27" combatPower="3" />
					<stage level="28" chance="0.0140" primarySkillLevel="28" combatPower="3" />
					<stage level="29" chance="0.0140" primarySkillLevel="29" combatPower="3" />
					<stage level="30" chance="0.0120" primarySkillLevel="30" combatPower="3" /> <!-- 1.2% -->
					<stage level="31" chance="0.0120" primarySkillLevel="31" combatPower="3" />
					<stage level="32" chance="0.0120" primarySkillLevel="32" combatPower="3" />
					<stage level="33" chance="0.0120" primarySkillLevel="33" combatPower="3" />
					<stage level="34" chance="0.0120" primarySkillLevel="34" combatPower="3" />
					<stage level="35" chance="0.0100" primarySkillLevel="35" combatPower="3" /> <!-- 1% -->
					<stage level="36" chance="0.0100" primarySkillLevel="36" combatPower="3" />
					<stage level="37" chance="0.0100" primarySkillLevel="37" combatPower="3" />
					<stage level="38" chance="0.0100" primarySkillLevel="38" combatPower="3" />
					<stage level="39" chance="0.0100" primarySkillLevel="39" combatPower="3" />
					<stage level="40" chance="0.0080" primarySkillLevel="40" combatPower="3" /> <!-- 0.8% -->
					<stage level="41" chance="0.0070" primarySkillLevel="41" combatPower="3" /> <!-- 0.7% -->
					<stage level="42" chance="0.0060" primarySkillLevel="42" combatPower="3" /> <!-- 0.6% -->
